---
galaxy_info:
  author: "Gabe Fierro"
  description: "Ansible role that installs the wavecmd for ipfs"
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: GenericUNIX
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: opensuse
      versions:
        - all
    - name: GenericBSD
      versions:
        - all
    - name: FreeBSD
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: SLES
      versions:
        - all
    - name: GenericLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - development
dependencies: []
